# jenkins服务编排文件
version: '3.0'
networks:
  jenkins-env:
    driver: bridge
services:
  #git
  git:
    image: bitnami/git
    networks:
      - jenkins-env
  # java 打包需要
  jdk:
    image: cytomine/java8
    networks:
      - jenkins-env
  # maven 打包需要
  maven:
    image: cytomine/java8
    volumes:
      - "./maven/settings.xml:/usr/share/maven/ref/"
    networks:
      - jenkins-env
  # node 前端项目构建需要
  node:
    image: node
    networks:
      - jenkins-env
  # jenkins
  jenkins:
    restart: always
    privileged: true
    image: jenkins/jenkins:lts-centos7-jdk8
    volumes:
      - "./jenkins/home:/var/jenkins_home"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-env